name: Terraform Plan

on:
  pull_request:
    branches:
      - prod

permissions:
  pull-requests: write
  contents: read

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout terraform repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Terraform Init
        run: |
          cd enviroments/prod
          terraform init

      - name: Terraform Plan
        id: plan
        run: |
          cd enviroments/prod
          # Initialize exit code
          TERRAFORM_EXIT_CODE=0
          
          # Run terraform plan and capture output
          terraform plan -input=false -no-color -detailed-exitcode > plan.txt || TERRAFORM_EXIT_CODE=$?
          
          # Add plan output to GitHub env
          echo "PLAN<<EOF" >> $GITHUB_ENV
          cat plan.txt >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          
          # Print exit code for debugging
          echo "Terraform exit code: $TERRAFORM_EXIT_CODE"
          
          # Check exit code
          case $TERRAFORM_EXIT_CODE in
            0)
              echo "No changes detected in plan"
              ;;
            2)
              echo "Changes detected in plan"
              ;;
            *)
              echo "Error during plan"
              cat plan.txt
              exit 1
              ;;
          esac

      - name: Add Plan Comment
        if: always()
        uses: actions/github-script@v6
        env:
          PLAN: ${{ env.PLAN }}
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            const output = `#### Terraform Plan Output
            
            <details><summary>Show Plan</summary>
            
            \`\`\`terraform
            ${process.env.PLAN}
            \`\`\`
            </details>`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.name,
              body: output
            })
