name: Terraform Deployment
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Remove default repo (dope)
        run: rm -rf ${{ github.workspace }}/*
      - name: Checkout terraform repository
        uses: actions/checkout@v3
        with:
           repository: abhijeetpoonia/asg
           ref: main
           path: asg
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
          
      - name: Terraform Init
        run: terraform init
        working-directory: asg/enviroments/dev

  validate:
    needs: init
    runs-on: ubuntu-latest
    steps:
      - name: Remove default repo (dope)
        run: rm -rf ${{ github.workspace }}/*
      - name: Checkout terraform repository
        uses: actions/checkout@v3
        with:
         repository: abhijeetpoonia/asg
         ref: main
         path: asg
            
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: asg/environments/dev
        
      - name: Terraform Validate
        run: terraform validate
        working-directory:  asg/enviroments/dev

  plan:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout terraform repository
        uses: actions/checkout@v3
        with:
          repository: abhijeetpoonia/asg
          ref: main
          path: asg
          
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
          
      - name: Terraform Plan
        run: terraform plan
        working-directory: asg/enviroments/dev

  apply:
    needs: plan
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout terraform repository
        uses: actions/checkout@v3
        with:
          repository: abhijeetpoonia/asg
          ref: main
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
          
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: environments/dev
