name: Terraform Plan

on:
  pull_request:
    branches:
      - prod

permissions:
  pull-requests: write
  contents: read

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout terraform repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Terraform Init
        working-directory: enviroments/prod
        run: terraform init

      - name: Terraform Plan
        working-directory: enviroments/prod
        id: tf-plan
        run: |
          terraform plan -input=false -no-color > plan.txt 2>&1
          if [ ! -s plan.txt ]; then echo "Terraform plan failed or no changes detected." > plan.txt; fi
        continue-on-error: true

      - name: Store Plan Output
        working-directory: enviroments/prod
        run: |
          echo "PLAN<<EOF" >> $GITHUB_ENV
          cat plan.txt >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Post Plan to PR
        uses: thollander/actions-comment-pull-request@v2
        if: github.event_name == 'pull_request'
        with:
          message: |
            #### Terraform Plan Output 🔍
            ```diff
            ${{ env.PLAN }}
            ```
          comment_tag: terraform_plan
          mode: recreate

      - name: Terraform Plan Status
        if: steps.tf-plan.outcome == 'failure'
        run: exit 1
