name: Terraform Deployment

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
           aws-access-key-id: ${{ secrets.aws_access_key_id }}
           aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
           aws-region: ap-south-1
      - name: Terraform Init
        run: terraform init
        working-directory: ./environments/dev

  validate:
    needs: init
    runs-on: ubuntu-latest
    steps:
      - name: Terraform Validate
        run: terraform validate
        working-directory: ./environments/dev

  plan:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - name: Terraform Plan
        run: terraform plan
        working-directory: ./environments/dev

  apply:
    needs: plan
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./environments/dev
